# Generated by Django 4.2.2 on 2023-07-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media/upload/')),
                ('solution', models.CharField(max_length=5000)),
            ],
        ),
    ]
