# Generated by Django 4.2.2 on 2023-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_upload_delete_course1'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='rollno',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='upload',
            name='solution',
            field=models.CharField(blank=True, default=' ', max_length=5000),
        ),
    ]
