# Generated by Django 4.2.2 on 2023-07-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='rollno',
        ),
    ]
